### ISSUE TITLE
x32dbg crashes when opening Scylla window

### ISSUE THREAD

**Issue by KurapicaBS** [x64dbg/GetCharABCWidthsI_cache#1]
x64 build : 22 -08-2017
Scylla x86 : 0.9.8

![2017-08-23_131704](https://user-images.githubusercontent.com/13423107/29611475-1b94f81e-87aa-11e7-86e7-d08dda46a15f.jpg)

**Comment by mrexodia** [comment]
I couldn't reproduce the issue, but it looks like it was silently fixed a few commits ago. Try again with a new release please 👍

**Comment by KurapicaBS** [comment]
I can confirm it's fixed, please close.
